In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling

In [2]:
df = pd.read_csv('h1b2018.csv')

/Users/bassim/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,case_number,visa_class,case_status,employer_name,employer_business_dba,employer_address,employer_city,employer_state,employer_postal_code,employer_country,...,new_concurrent_employment,change_employer,amended_petition,pw_wage_level,pw_source,pw_source_year,pw_source_other,support_h1b,labor_con_agree,public_disclosure_location
0,I-200-18178-159595,H-1B,CERTIFIED,DELOITTE CONSULTING LLP,NaN,1700 MARKET STREET,PHILADELPHIA,PA,19103,UNITED STATES OF AMERICA,...,0.0,0.0,3.0,Level I,OES,2017.0,OFLC ONLINE DATA CENTER,NaN,NaN,NaN
1,I-200-18107-532650,H-1B,CERTIFIED,METASENSE INC.,NaN,403 COMMERCE LANE,WEST BERLIN,NJ,08091,UNITED STATES OF AMERICA,...,0.0,0.0,0.0,Level II,OES,2018.0,OFLC ONLINE DATA CENTER,Y,Y,NaN
2,I-200-18183-381518,H-1B,CERTIFIED,"DFG INVESTMENT ADVISERS, INC.",NaN,747 THIRD AVENUE,NEW YORK,NY,10017,UNITED STATES OF AMERICA,...,0.0,0.0,0.0,Level IV,OES,2017.0,OFLC ONLINE DATA CENTER,NaN,Y,NaN
3,I-200-18149-760149,H-1B,CERTIFIED,TATA CONSULTANCY SERVICES LIMITED,NaN,9201 CORPORATE BOULEVARD,ROCKVILLE,MD,20850,UNITED STATES OF AMERICA,...,0.0,1.0,0.0,Level II,OES,2017.0,OFLC ONLINE DATA CENTER,Y,NaN,NaN
4,I-200-18222-447165,H-1B,CERTIFIED,"I3 INFOTEK, INC.",NaN,120 WOOD AVENUE S,ISELIN,NJ,08830,UNITED STATES OF AMERICA,...,0.0,0.0,0.0,Level II,OES,2018.0,OFLC ONLINE DATA CENTER,Y,NaN,NaN

In [9]:
df.columns

Index(['case_number', 'visa_class', 'case_status', 'employer_name',
       'employer_business_dba', 'employer_address', 'employer_city',
       'employer_state', 'employer_postal_code', 'employer_country',
       'employer_province', 'employer_phone', 'employer_phone_ext',
       'naics_code', 'soc_code', 'soc_name', 'job_title', 'total_workers',
       'case_submitted', 'decision_date', 'employment_start_date',
       'employment_end_date', 'full_time_position', 'prevailing_wage',
       'pw_unit_of_pay', 'wage_rate_of_pay_from', 'wage_rate_of_pay_to',
       'wage_unit_of_pay', 'worksite_city', 'worksite_county',
       'worksite_state', 'worksite_postal_code', 'agent_attorney_name',
       'agent_representing_employer', 'agent_attorney_city',
       'agent_attorney_state', 'h1b_dependent', 'willful_violator',
       'original_cert_date', 'new_employment', 'continued_employment',
       'change_previous_employment', 'new_concurrent_employment',
       'change_employer', 'amended_petition', 'pw_wage_level', 'pw_source',
       'pw_source_year', 'pw_source_other', 'support_h1b', 'labor_con_agree',
       'public_disclosure_location'],
      dtype='object')

In [4]:
df.shape

(654360, 52)

In [11]:
pandas_profiling.ProfileReport(df[['visa_class','employer_name','employer_address','employer_city','employer_state','employer_province','prevailing_wage','job_title','full_time_position','pw_unit_of_pay']])

/Users/bassim/anaconda3/lib/python3.6/site-packages/pandas_profiling/describe.py:404: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)